project:
  type: book
  output-dir: docs

book:
  title: "Book"
  author: "Chiara Marti"
  date: today
  downloads: pdf
  chapters:
    - index.qmd
    - k1.qmd
    - k2.qmd
    - k3.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

